# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "build(dependencies)"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "dependabot"
    ignore:
      # Security updates are not affected by this ignore filter and still will be updated
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
