# This workflow will build a Java project with Gradle

name: Run build and tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    environment: CIRelease
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - run: git fetch --all --tags

      - name: Create .gradle dir
        run: mkdir -p $HOME/.gradle

      - name: Build and test with Gradle
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=true"
        run: ./gradlew build test -s

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
            files: build/test-results/**/*.xml
